name=FelixSense
version=1.0.0
author=Felix Ochoa
maintainer=Felix Ochoa
sentence=A lightweight Arduino library for analog sensors with photoresistors, thermistors, and potentiometers.
paragraph=Provides smoothing, normalization, mapped outputs, calculations, and easy sensor-specific classes.
category=Sensors
url=https://github.com/felixthecat8a/FelixSense
architectures=*
