name: Spell Check

on:
  push:
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
  repository_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Spell check
        uses: codespell-project/actions-codespell@master
